version: 2
updates:
  - package-ecosystem: npm
    directory: /npm-package
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      jest:
        patterns:
          - "jest"
          - "@types/jest"
          - "ts-jest"
          - "babel-jest"

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      wasm-bindgen:
        patterns:
          - "wasm-bindgen*"
          - "js-sys"
          - "web-sys"
      tsify:
        patterns:
          - "tsify*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
