/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_dcapi_free: (a: number, b: number) => void;
export const dcapi_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: any) => any;
export const dcapi_create_new_session: (a: number) => any;
export const dcapi_initiate_request: (a: number, b: number, c: number, d: number, e: number, f: any, g: number, h: number) => any;
export const dcapi_submit_response: (a: number, b: number, c: number, d: number, e: number, f: any) => any;
export const __wbg_jsdcapisessiondriver_free: (a: number, b: number) => void;
export const __wbg_jsoid4vpsessionstore_free: (a: number, b: number) => void;
export const jsoid4vpsessionstore_new: (a: any) => number;
export const jsoid4vpsessionstore_createMemoryStore: () => [number, number, number];
export const jsoid4vpsessionstore_generateSessionUuid: () => [number, number];
export const jsoid4vpsessionstore_parseUuid: (a: number, b: number) => [number, number, number, number];
export const jsoid4vpsessionstore_sessionToJs: (a: any) => [number, number, number];
export const jsoid4vpsessionstore_statusToJs: (a: any) => [number, number, number];
export const jsoid4vpsessionstore_createStatusSentRequestByReference: () => any;
export const jsoid4vpsessionstore_createStatusSentRequest: () => any;
export const jsoid4vpsessionstore_createStatusReceivedResponse: () => any;
export const jsoid4vpsessionstore_createStatusCompleteSuccess: (a: any) => [number, number, number];
export const jsoid4vpsessionstore_createStatusCompleteFailure: (a: number, b: number) => any;
export const jsoid4vpsessionstore_createStatusCompleteError: (a: number, b: number) => any;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure1630_externref_shim: (a: number, b: number, c: any) => void;
export const closure1993_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
